CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921025942_InitialCreate') THEN
    CREATE TABLE raw_epg_snapshots (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        epg_date date NOT NULL,
        fetched_at_utc timestamp with time zone NOT NULL,
        sha256 character varying(64) NOT NULL,
        payload jsonb NOT NULL,
        CONSTRAINT "PK_raw_epg_snapshots" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921025942_InitialCreate') THEN
    CREATE INDEX ix_raw_epg_snapshots_epg_date_fetched_at ON raw_epg_snapshots (epg_date, fetched_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921025942_InitialCreate') THEN
    CREATE UNIQUE INDEX ux_raw_epg_snapshots_epg_date_sha256 ON raw_epg_snapshots (epg_date, sha256);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921025942_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260921025942_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921031900_AllowRepeatedEpgSnapshotHashes') THEN
    DROP INDEX ux_raw_epg_snapshots_epg_date_sha256;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921031900_AllowRepeatedEpgSnapshotHashes') THEN
    CREATE INDEX ux_raw_epg_snapshots_epg_date_sha256 ON raw_epg_snapshots (epg_date, sha256);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921031900_AllowRepeatedEpgSnapshotHashes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260921031900_AllowRepeatedEpgSnapshotHashes', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921034818_RenameEpgSnapshotHashIndex') THEN
    ALTER INDEX ux_raw_epg_snapshots_epg_date_sha256 RENAME TO ix_raw_epg_snapshots_epg_date_sha256;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921034818_RenameEpgSnapshotHashIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260921034818_RenameEpgSnapshotHashIndex', '10.0.12');
    END IF;
END $EF$;
COMMIT;

