// <auto-generated />
using System;
using MOCTools.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MOCTools.Data.Migrations
{
    [DbContext(typeof(MOCToolsDbContext))]
    [Migration("20260921034818_RenameEpgSnapshotHashIndex")]
    partial class RenameEpgSnapshotHashIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MOCTools.Data.Entities.RawEpgSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("EpgDate")
                        .HasColumnType("date")
                        .HasColumnName("epg_date");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.HasKey("Id");

                    b.HasIndex("EpgDate", "FetchedAtUtc")
                        .HasDatabaseName("ix_raw_epg_snapshots_epg_date_fetched_at");

                    b.HasIndex("EpgDate", "Sha256")
                        .HasDatabaseName("ix_raw_epg_snapshots_epg_date_sha256");

                    b.ToTable("raw_epg_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
